var jugadores = [
    {
        nombre: "Agustín",
        apellido: "Pedroso",
        posicion: "Arquero",
        camiseta: 12,
        apodo: '"Cuervo"',
        goles:{
            menoresa: Sumar_goles("Pedroso",partidos_menoresa),
            menoresb: Sumar_goles("Pedroso",partidos_menoresb),
            menoresc: Sumar_goles("Pedroso",partidos_menoresc),
            menoresd: Sumar_goles("Pedroso",partidos_menoresd),
            copa: Sumar_goles("Pedroso",partidos_copa),
        },
        expulsiones: 0,
        ganados: 25,
        empatados: 15,
        perdidos: 3,
        
        foto:{ 
          carnet:"images/jugadores/carnet/apedroso_carnet.jpeg" ,
          alt:"Foto Agustín Pedroso" ,
          cancha: "images/jugadores/cancha/cuervo.jpg",
        },
        momento:"",
    },
    {
      nombre: "Lail",
      apellido: "Furchi",
      posicion: "Defensor",
      camiseta: 2,
      apodo:"",
      goles:{
          menoresa: Sumar_goles("Furchi",partidos_menoresa),
          menoresb: Sumar_goles("Furchi",partidos_menoresb),
          menoresc: Sumar_goles("Furchi",partidos_menoresc),
          menoresd: Sumar_goles("Furchi",partidos_menoresd),
          copa: Sumar_goles("Furchi",partidos_copa),
      },
      expulsiones: 0,
      ganados: 25,
      empatados: 13,
      perdidos: 3,
      
      foto:{ 
           carnet:"images/jugadores/carnet/lfurchi_carnet.jpg" ,
           alt:"Foto Lail Furchi" ,
           cancha: "images/jugadores/cancha/lail.jpg",
       },
       momento:"",
      },  
      {
          nombre: "Martín",
          apellido:"Laski",
          posicion: "Defensor",
          camiseta: 3,
          apodo:"",
          goles:{
            menoresa: Sumar_goles("Laski",partidos_menoresa),
            menoresb: Sumar_goles("Laski",partidos_menoresb),
            menoresc: Sumar_goles("Laski",partidos_menoresc),
            menoresd: Sumar_goles("Laski",partidos_menoresd),
            copa: Sumar_goles("Laski",partidos_copa),
          },
          expulsiones: 0,
          ganados: 24,
          empatados: 13,
          perdidos: 3,
          
          foto:{ 
               carnet:"images/jugadores/carnet/default-user.jpg" ,
               alt:"Foto Martín Laski" ,
               cancha: "images/jugadores/cancha/marto.jpg",
           },
           momento:"",
      }, 
      {
          nombre: "Nicolás", 
          apellido:"Gamba",
          posicion: "Volante",
          camiseta: 4,
          apodo:"",
          goles:{
            menoresa: Sumar_goles("Gamba",partidos_menoresa),
            menoresb: Sumar_goles("Gamba",partidos_menoresb),
            menoresc: Sumar_goles("Gamba",partidos_menoresc),
            menoresd: Sumar_goles("Gamba",partidos_menoresd),
            copa: Sumar_goles("Gamba",partidos_copa),
          },
          expulsiones: 0,
          ganados: 23,
          empatados: 14,
          perdidos: 3,
          
          foto:{ 
               carnet:"images/jugadores/carnet/default-user.jpg" ,
               alt:"Foto Nicolás Gamba" ,
               cancha: "images/jugadores/cancha/nico.jpeg",
           },
           momento:"",
      }, 
      {
          nombre: "Tomás",
          apellido: "Tenconi",
          posicion: "Volante",
          camiseta: 5,
          apodo:"",
          goles:{
            menoresa: Sumar_goles("Tenconi",partidos_menoresa),
            menoresb: Sumar_goles("Tenconi",partidos_menoresb),
            menoresc: Sumar_goles("Tenconi",partidos_menoresc),
            menoresd: Sumar_goles("Tenconi",partidos_menoresd),
            copa: Sumar_goles("Tenconi",partidos_copa),
          },
          expulsiones: 0,
          ganados: 27,
          empatados: 14,
          perdidos: 3,
          
          foto:{ 
               carnet:"images/jugadores/carnet/ttenconi_carnet.jpeg" ,
               alt:"Foto Tomás Tenconi" ,
               cancha: "images/jugadores/cancha/tenco.jpeg",
           },
           momento:"Era un domingo al mediodía de 2018. La Horacio Pagani había salido campeón un rato antes que nosotros y nos enfrentabamos frente a Segundo Semestre. El triunfo era necesario para pelear el puesto de ascenso directo, el consuelo que nos quedaba. Arrancamos perdiendo 1-0 y en el entretiempo Nico nos dió una charla imborrable para quienes estuvimos ese día. Cuando parecía que se nos escapaba el ascenso de manera increible, otra vez Nico nos ponía en partido. Gol de tiro libre al ángulo difícil de repetir. Faltando dos minutos, la victoria estuvo en mis pies y la desperdicié. Sin embargo, por esas cosas del destino, cosas locas, tuve la oportunidad, casi idéntica a la anterior, de ponernos adelante en el marcador. Tras una carrera maratónica y un hombro contra hombro inexplicable bajo las leyes de la física, en la última jugada del partido, tuve la posibilidad de ponernos por delante en el marcador. Fue de las pocas veces que se me frenó el tiempo por un segundo dentro de tanta aceleración. El impacto del esférico en la red no lo voy a olvidar jamás, pero menos voy a olvidar la cara de alegría de mis compañeros corriendo hacia mí después de hacer ese gol, que nos permitiría llegar al último partido con posibilidad de ascender directo.",
      },
      {
          nombre: "Román", 
          apellido: "Daffunchio",
          posicion: "Volante",
          camiseta: 8,
          apodo:"",
          goles:{
            menoresa: Sumar_goles("Daffunchio",partidos_menoresa),
            menoresb: Sumar_goles("Daffunchio",partidos_menoresb),
            menoresc: Sumar_goles("Daffunchio",partidos_menoresc),
            menoresd: Sumar_goles("Daffunchio",partidos_menoresd),
            copa: Sumar_goles("Daffunchio",partidos_copa),
          },
          expulsiones: 0,
          ganados: 26,
          empatados: 13,
          perdidos: 3,
          
          foto:{ 
               carnet:"images/jugadores/carnet/default-user.jpg" ,
               alt:"Foto Román Daffunchio" ,
               cancha: "images/jugadores/cancha/roman.jpg",
           },
           momento:"",
      }, 
      {
          nombre: "Juan",
          apellido: "Erbin",
          posicion: "Delantero",
          camiseta: 9,
          apodo: "Bitxo",
          goles:{
            menoresa: Sumar_goles("Erbin",partidos_menoresa),
            menoresb: Sumar_goles("Erbin",partidos_menoresb),
            menoresc: Sumar_goles("Erbin",partidos_menoresc),
            menoresd: Sumar_goles("Erbin",partidos_menoresd),
            copa: Sumar_goles("Erbin",partidos_copa),
          },
          expulsiones: 1,
          ganados: 24,
          empatados: 13,
          perdidos: 3,
          
          foto:{ 
               carnet:"images/jugadores/carnet/default-user.jpg" ,
               alt:"Foto Juan Erbin" ,
               cancha: "images/jugadores/cancha/bitxo.jpeg",
           },
           momento:"",
      }, 
      {
          nombre: "Juan Martín",
          apellido: "Acquafresca",
          posicion: "Delantero",
          camiseta: 10,
          apodo:"",
          goles:{
            menoresa: Sumar_goles("Acquafresca",partidos_menoresa),
            menoresb: Sumar_goles("Acquafresca",partidos_menoresb),
            menoresc: Sumar_goles("Acquafresca",partidos_menoresc),
            menoresd: Sumar_goles("Acquafresca",partidos_menoresd),
            copa: Sumar_goles("Acquafresca",partidos_copa),
          },
          expulsiones: 0,
          ganados: 20,
          empatados: 10,
          perdidos: 2,
          
          foto:{ 
               carnet:"images/jugadores/carnet/default-user.jpg" ,
               alt:"Foto Juan Acquafresca" ,
               cancha: "images/jugadores/cancha/acqua.jpg",
           },
           momento:"",
      },  
      {
          nombre: "Genaro",
          apellido: "Blumetti",
          posicion: "Defensor",
          camiseta: 11,
          apodo:"",
          goles:{
            menoresa: Sumar_goles("Blumetti",partidos_menoresa),
            menoresb: Sumar_goles("Blumetti",partidos_menoresb),
            menoresc: Sumar_goles("Blumetti",partidos_menoresc),
            menoresd: Sumar_goles("Blumetti",partidos_menoresd),
            copa: Sumar_goles("Blumetti",partidos_copa),
          },
          expulsiones: 0,
          ganados: 27,
          empatados: 15,
          perdidos: 3,
          
          foto:{ 
               carnet:"images/jugadores/carnet/default-user.jpg" ,
               alt:"Foto Genaro Blumetti" ,
               cancha: "images/jugadores/cancha/gena.jpg",
           },
           momento:"",
      }, 
      {
          nombre: "Facundo",
          apellido: "Jannello",
          posicion: "Defensor",
          camiseta: 14,
          apodo:"",
          goles:{
            menoresa: Sumar_goles("Jannello",partidos_menoresa),
            menoresb: Sumar_goles("Jannello",partidos_menoresb),
            menoresc: Sumar_goles("Jannello",partidos_menoresc),
            menoresd: Sumar_goles("Jannello",partidos_menoresd),
            copa: Sumar_goles("Jannello",partidos_copa),
          },
          expulsiones: 3,
          ganados: 23,
          empatados: 14,
          perdidos: 2,
          
          foto:{ 
               carnet:"images/jugadores/carnet/fjannello_carnet.jpeg" ,
               alt:"Foto Facundo Jannello" ,
               cancha: "images/jugadores/cancha/facu.jpg",
           },
           momento:'Días antes de compré unos botines. "No da para más", me dije. Usé todo el torneo de la D unos botines de Acqua porque los míos se estropearon en la segunda fecha.  Los estrené el día del partido, creía que me iban a dar suerte. Lo sabía. Sabía que me iban a  dar la suerte que nunca tengo. Sabía que tenía que subir, cuando nunca subo. Sabía dónde caería la pelota, cuando nunca me cae. Sabía qué movimiento hacer para ponerla dónde sabía que no iban a llegar, cuando nunca se me dió por esas cosas. Sabía que el partido se iba a terminar ahí y que había llegado nuestro momento. Pero lo que realmente no sabía, es que era posible que todo suceda. No me incorporé. Me quedé escuchando ese silencio, como suspendido. Miré al colegiado que marcaba el centro como única reacción. Esperé dos segundos a que me anule el sueño. Esperé dos segundos a despertarme. Simplemente esperé ahí, flotando en el momento, atónito y sin reacción. El brazo de Tenco se me cruzó por el cuello, me levantó y me arrastró hasta la esquina de la cancha 1. Llegó Bitxo enseguida y se sumó a la montaña. Se sumaron otros cinco. Todo MaFaVi. Y solo en esa montaña de sudor y de  tierra enfrente de nuestros rivales, fue que pude largar las primeras palabras. No podía ni gritar. Estaba ahogado ya sea porque me apretaban los pulmones o porque seguía en shock. Finalmente, pude soltar débilmente la frase que todos sabíamos, pero solo yo pude decir en paralelo al grito ensordecedor de mis compañeros: "Lo hicimos".',
      }, 
      {
          nombre: "Juan Bautista",
          apellido: "Cellerino",
          posicion: "Volante",
          camiseta: 30,
          apodo:'"Patria"',
          goles:{
            menoresa: Sumar_goles("Cellerino",partidos_menoresa),
            menoresb: Sumar_goles("Cellerino",partidos_menoresb),
            menoresc: Sumar_goles("Cellerino",partidos_menoresc),
            menoresd: Sumar_goles("Cellerino",partidos_menoresd),
            copa: Sumar_goles("Cellerino",partidos_copa),
          },
          expulsiones: 1,
          ganados: 25,
          empatados: 15,
          perdidos: 3,
          
          foto:{ 
               carnet:"images/jugadores/carnet/jcellerino_carnet.jpeg" ,
               alt:"Foto Juan Cellerino" ,
               cancha: "images/jugadores/cancha/patria.jpeg",
           },
           momento:'Mi momento favorito con el MaFaVi F. C. fue el 24 de noviembre de 2019. MaFaVi debía jugar a las 8 de la mañana contra Pancho I, rival directo en la pelea por los puestos del ascenso. Los rivales de turno avisaron en los días previos al encuentro que no iban a presentarse, pero nosotros, desconfiados de todo rival, fuimos a jugar el partido. A las 7:30am estabamos todos cambiados y haciendo el calentamiento como si el partido fuera a disputarse, a pesar de que los rivales nunca llegaron. Finalmente, terminamos haciendo un torneo de penales entre nosotros para aprovechar que ya estabamos con los botines puestos. Es mi episodio favorito porque representa la enfermedad y el sentimiento por el MaFaVi, tanto de los 12 jugadores como de algunos hinchas que vinieron a hacer el aguante un domingo a primera hora.',
      }, 
      {
          nombre: "Andrés",
          apellido: "Lambertini",
          posicion: "Defensor",
          camiseta: 33,
          apodo:'"Tito"',
          goles:{
            menoresa: Sumar_goles("Lambertini",partidos_menoresa),
            menoresb: Sumar_goles("Lambertini",partidos_menoresb),
            menoresc: Sumar_goles("Lambertini",partidos_menoresc),
            menoresd: Sumar_goles("Lambertini",partidos_menoresd),
            copa: Sumar_goles("Lambertini",partidos_copa),
          },
          expulsiones: 1,
          ganados: 17,
          empatados: 8,
          perdidos: 1,
          
          foto:{ 
               carnet:"images/jugadores/carnet/default-user.jpg" ,
               alt:"Foto Andrés Lambertini" ,
               cancha: "images/jugadores/cancha/tito.jpg",
           },
           momento:"",
      },
      
      
      

];